### ISSUE TITLE
Custom Amps

### ISSUE THREAD

**Issue by boharaganga** [aborroy/alfresco-docker-best-practices#2]
Hi @aborroy How do we install custom amps in the Enterprise version? Do we need to put in certain directory and alfresco-mmt picks it up or do we need to customize the Dockerfile for alfresco service?

**Comment by aborroy** [comment]
You need to customize the Dockerfile for Alfresco service, something similar to:
https://github.com/Alfresco/alfresco-docker-installer/blob/master/generators/app/templates/images/alfresco/Dockerfile#L11

**Comment by boharaganga** [comment]
Closing this. @aborroy's message above answers the question I had.
